### ISSUE TITLE
check_package_status does not return correct value under Ubuntu 14.04

### ISSUE THREAD

**Issue by briemla** [jacobzelek/rtl_sdr_kit#12]
On a fresh installed Ubuntu 14.04 check_package_status does not return the expected value (ii or un) when checking the status of QT5 installation in line 46.

After a change of the line 33:
RES=`dpkg -l $1 2>&1 | sed -n '6p' | awk '{print $1}'`

to
RES=`dpkg -l $1 2>&1 | sed -n '7p' | awk '{print $1}'`

the script is able to run.

**Comment by jacobzelek** [comment]
Put that piece of code in
